name: babble
description: "A social audio room app for your gang"
publish_to: 'none'
version: 1.0.2+3
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  cached_network_image: ^3.3.1
  cached_video_player: ^2.0.4
  cloud_firestore: ^4.15.10
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.6
  emoji_picker_flutter: ^2.1.1
  enough_giphy_flutter: ^0.4.1
  file_picker: ^6.2.1
  firebase_analytics: ^10.10.5
  firebase_app_check: ^0.2.1+18
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_crashlytics: ^3.5.5
  firebase_storage: ^11.6.10
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.7+1
  flutter_riverpod: ^2.5.1
  flutter_sound_record: ^3.3.2
  flutter_super_html_viewer: ^0.1.0
  get: ^4.6.6
  image_picker: ^1.0.7
  intl: ^0.18.1
  loading_animation_widget: ^1.2.0+4
  meta: ^1.11.0
  mime: ^1.0.5
  open_filex: ^4.4.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pinput: ^4.0.0
  shared_preferences: ^2.2.3
  swipe_to: ^1.0.2
  transparent_image: ^2.0.1
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  zego_express_engine: ^3.14.5+2
  zego_uikit_prebuilt_live_audio_room: ^3.6.7

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 23 # android min sdk min:16, default 21
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  adaptive_icon_background: "#ffffff"
  web:
    generate: true
    background_color: "#7F7F7E"
    theme_color: "#7F7F7E"
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true

flutter:
  fonts:
    - family: Jua
      fonts:
        - asset: assets/fonts/Jua-Regular.ttf
          weight: 400
    - family: Hind
      fonts:
        - asset: assets/fonts/Hind-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Hind-Medium.ttf
          weight: 500
        - asset: assets/fonts/Hind-Regular.ttf
          weight: 400
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Medium.ttf
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
  uses-material-design: true

  assets:
    - assets/images/
