// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvyR5rx84n-_eDImC9hKUQk3od3fEqRLk',
    appId: '1:953387577807:web:9822a4702c0fca029fe2ba',
    messagingSenderId: '953387577807',
    projectId: 'babble-23d3e',
    authDomain: 'babble-23d3e.firebaseapp.com',
    storageBucket: 'babble-23d3e.appspot.com',
    measurementId: 'G-02N225WXE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7-pRPlZ-wLEODMuQk29CjsbL7QlzVCdE',
    appId: '1:953387577807:android:aadd1ad5458d69e09fe2ba',
    messagingSenderId: '953387577807',
    projectId: 'babble-23d3e',
    storageBucket: 'babble-23d3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRGHZzeoD2zq_gT03DuXkGRyQa_bwEnS8',
    appId: '1:953387577807:ios:0eaaa3cc3ddc205f9fe2ba',
    messagingSenderId: '953387577807',
    projectId: 'babble-23d3e',
    storageBucket: 'babble-23d3e.appspot.com',
    iosBundleId: 'com.example.babble1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRGHZzeoD2zq_gT03DuXkGRyQa_bwEnS8',
    appId: '1:953387577807:ios:4ea08558959611659fe2ba',
    messagingSenderId: '953387577807',
    projectId: 'babble-23d3e',
    storageBucket: 'babble-23d3e.appspot.com',
    iosBundleId: 'com.example.babble1.RunnerTests',
  );
}
