import 'package:flutter/material.dart';

//Registration and OTP
const otpVerifyButtonBg = Color.fromARGB(255, 105, 113, 146);
const chatScreenDateBg = Color.fromARGB(255, 87, 88, 89);
//InApp
const bodyBackgroundColor =
//Color(0xFFE0D6D6)
        Color(0xFF7F7F7E),
    bottomNavBarColor = Color(0xFF1F384F),
    roomTileSpeakingMicIcon = Color.fromARGB(255, 14, 172, 19),
    otpSubColor = regTitleColor,
    regTitleColor = Color.fromRGBO(30, 35, 44, 1),
    kWhite = Colors.white,
    regOtpFieldBgColor = kWhite,
    getStartedBg = Color.fromARGB(255, 121, 124, 123),
    titleColor = Color.fromRGBO(7, 24, 85, 1),
    buttonBorder = Color.fromARGB(255, 30, 35, 44),
    babbleTitleColor = Color(0xFF071855),
    searchBoxBg = Color.fromARGB(255, 118, 117, 117),
    searchBoxTextColor = Color.fromARGB(255, 207, 204, 204),
    chatListLastMsgTime = Colors.black,
    roomMemberNameTextColor = Color.fromARGB(255, 92, 89, 89),
    chatListTileLastMsgTextColor = Color.fromARGB(255, 237, 234, 234),
    roomsListTileSpeakingTitleTextColor = Color.fromARGB(255, 255, 249, 249),
    roomMuteRedGradientColorsList = [Color(0xFFE81F1F), Color(0xFF730808)],
    roomMuteGreenGradientColorsList = [Color(0xFF53E81F), Color(0xFF107308)],
    roomBackgroundGradientColorsList = [
      Color(0xFFE8DCDC),
      Color(0xFFA29F9F),
    ],
    appBarOnlineDotCircleColor = Color.fromARGB(255, 11, 223, 18),
    roomBgGradientList = [Color(0xFFA29F9F), Color(0xFFE8DCDC)],
    roomControlCloseRoomButtonRedColor = Color(0xFFC62222),
    roomControlCloseRoomButtonGreenColor = Colors.green,
    roomControlMembersListBgColor = Color.fromARGB(255, 139, 153, 167),
    roomControlMuteAllBg = Color(0xFF9B9A9A),
    roomControlInactiveMuteBg = Color(0xFF837D7D),
    roomControlActiveMuteBg = Color(0xFFBB2828),
    roomControlExitIconBg = Color(0xFFC62222),
    chatBoxColor = Color(0xFFF3F6F6),
    senderMessageCardColor = Color(0xFFF2F7FB),
    myMessageCardColor = babbleTitleColor,
    chatAppBarBg = searchBoxBg,
    myMessageCardTimeColor = Color(0xFF999F9D),
    senderMessageCardTimeColor = Colors.black87,
    unseenMsgTickColor = Colors.white60,
    seenMsgTickColor = Colors.blue,
    myMessageNameColor = Colors.white,
    senderMessageReplyBgColor = Color(0xFFBDBDBD),
    senderMessageNameColor = Colors.black,
    floatingActionButtonIconColor = Colors.white,
    appbarBackButtonColor = Colors.white,
    settingsNameSheetBg = Color.fromARGB(255, 55, 53, 53),
    profilePicViewerBg = Colors.black,
    profilePicViewerTitleColor = Colors.white,
    profilePicViewerNoImageColor = Colors.white30;
